name: amanda_longo_esteticista
description: Especializada em estética corporal e facial

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  url_launcher: 6.1.10
  seo_renderer: 0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Agrandir
      fonts:
        - asset: assets/fonts/Agrandir-Regular.otf
